
name: Deploy SRE-Load-Balancer

on:
  pull_request:
    branches:
      - main

jobs:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck on scripts
        run: |
          if command -v shellcheck; then shellcheck scripts/*.sh; else echo 'shellcheck not installed'; fi
      - name: Check PowerShell scripts
        run: |
          pwsh -Command "Get-ChildItem scripts/*.ps1 | ForEach-Object { Write-Host Checking $_; }"
